import com.cleanroommc.groovyscript.compat.mods.immersiveengineering.Excavator
log.debug("Removing all Excavator veins...")
// Excavator.removeAll()
mods.immersiveengineering.excavator.removeAll()
addOres()
def addOres(){
Excavator.recipeBuilder()
    .name('garnet')
    // .ore(item('gtclassic:redgarnet_gem'))
    // .ore(item('gtclassic:yellowgarnet_gem'))
    .ore('gemRedGarnet',10)
    .ore('gemYellowGarnet',10)
    .weight(2000)
    .fail(0.1)
    .dimension(1)
    .register()
Excavator.recipeBuilder()
    .name('bauxite')
    .ore('oreBauxite',70)
    .weight(10000)
    .fail(0.3)
    .dimension(1)
    .register()
Excavator.recipeBuilder()
    .name('galena')
    .ore('oreGalena',80)
    .weight(20000)
    .fail(0.2)
    .dimension(1)
    .register()
Excavator.recipeBuilder()
    .name('cinnabar')
    .ore('oreCinnabar',30)
    .ore('oreRedstone',50)
    .ore('oreClathrateRedstone',10)
    .weight(15000)
    .fail(0.5)
    .dimension(1)
    .register()
Excavator.recipeBuilder()
    .name('sheldonite')
    .ore('oreSheldonite',10)
    .register()
}